### ISSUE TITLE
Add sheetify as default transform

### ISSUE THREAD

**Issue by auggod** [jallajs/jalla#2]
I wonder if sheetify should be added as a default transform. Adding sheetify as custom transform works in development mode but it fails in production mode because it's ran after babelify. 
The error is similar to https://github.com/stackcss/sheetify/issues/79 though we're not talking about es modules.
``search.js:3 Uncaught TypeError: 0 is not a function``

I attempted to modify `jalla/script.js` to include sheetify before last babelify transform but I ran into more problems.

**Comment by tornqvist** [comment]
Part of the reason why I set off to create jalla was because I didn't like how Bankai (which uses sheetify) made the CSS dependent on the Browserify pipeline. In my experience, compiling large JavaScript applications can take up to several seconds, and having to wait for the JavaScript to compile to apply changes made in CSS was a source of frustration.

As of right now, there's no way for the JavaScript bundle to generate CSS. But with the new pipeline being introduced in the prerelease of v1, this could probably be achieved in user land.

I'm thinking something in line with:

```javascript
var jalla = require('jalla')
var app = jalla('index.js')

// add our custom sheetify transform before babel
app.pipeline.get('scripts').unshift(require('./my-sheetify-bundler'))

app.listen(8080)
```

We'd still have to figure our how the styles bundler could pick up what CSS has been extracted with sheetify but I'm open to ideas.

**Comment by auggod** [comment]
Thank you! I probably can close this issue now.
